services:
  flask_app_1:
    build: .
    ports:
      - "5001:5000"
    networks:
      - flashcards_net

  flask_app_2:
    build: .
    ports:
      - "5002:5000"
    networks:
      - flashcards_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app_1
      - flask_app_2
    networks:
      - flashcards_net

networks:
  flashcards_net:
    driver: bridge
